[tool.poetry]
name = "sql2json"
version = "0.1.4"
description = "SQL query to JSON"
authors = ["Francisco Perez <fsistemas@gmail.com>"]

repository = "https://github.com/fsistemas/sql2json"
homepage = "https://github.com/fsistemas/sql2json"

keywords = ['sql', 'json', 'tool']

[tool.poetry.dependencies]
python = "^3.5"
SQLAlchemy = "^1.3.12"
fire = "^0.2.1"

[tool.poetry.dev-dependencies]
flake8 = "^3.7.9"
mypy = "^0.761"
pytest = "^5.3.2"


[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
